spring:
  r2dbc:
    username: postgres
    password:
    url: r2dbc:postgresql://localhost:5432/intershop
  application:
    name: intershop
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#  datasource:
#    url: r2dbc:postgresql://localhost:5432/intershop
#    username: postgres
#    password:
  liquibase:
#    url: jdbc:postgresql://localhost:5432/intershop
    change-log: classpath:db/changelog/changelog.yml
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      thymeleaf: DEBUG
      springframework:
        web: DEBUG