spring:
  application:
    name: intershop
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/intershop
    username: postgres
    password:
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

logging:
  level:
    org:
      thymeleaf: DEBUG
      springframework:
        web: DEBUG