openapi: 3.0.3
info:
  title: Интернет-магазин API
  version: 1.0.0

paths:
  /api/products:
    get:
      tags: [Products]
      operationId: getProducts
      responses:
        '200':
          description: Список товаров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number