spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: postgres
    password:
  application:
    name: intershop
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  liquibase:
    url: jdbc:postgresql://localhost:5432/intershop  # Важно: postgres вместо localhost
    user: postgres
    password: ''
    change-log: classpath:db/changelog/changelog.yml
    enabled: true
logging:
  level:
    org:
      thymeleaf: DEBUG
      springframework:
        web: DEBUG